# Generated by Django 3.1.8 on 2021-04-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=200)),
            ],
        ),
    ]
